sudo: false

language: ruby

rvm:
  - 2.2.5

env:
  - TRAVIS_NODE_VERSION="4"
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - npm install -g grunt-cli
  - npm install
  - bundle install

script:
  - npm run lint -s
  - npm test
  - grunt build
  - bundle exec jekyll build