sudo: false

language: ruby

rvm:
  - 2.2.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - npm install -g grunt-cli
  - npm install
  - bundle install

script:
  - grunt test
  - grunt build
  - bundle exec jekyll build
  - htmlproofer ./_site --allow-hash-href