sudo: false

language: ruby

rvm:
  - 2.4.0

before install:
  - node --version

install:
  - npm install -g grunt-cli
  - npm install
  - bundle install

script:
  - npm run lint -s
  - npm test
  - grunt build
  - bundle exec jekyll build