sudo: false

language: ruby

rvm:
  - 2.2.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TRAVIS_NODE_VERSION="4"

install:
  - npm install -g grunt-cli
  - npm install
  - bundle install

script:
  - npm run lint -s
  - npm test
  - grunt build
  - bundle exec jekyll build