sudo: false

language: ruby

rvm:
  - 2.4.0

before install:
  - . $HOME/.nvm/nvm.sh

install:
  - nvm install stable
  - nvm use stable
  - npm install -g grunt-cli
  - npm install
  - bundle install

script:
  - npm run lint -s
  - npm test
  - grunt build
  - bundle exec jekyll build