# Site settings
title: TEI Viewer
author: Alexander Mendes
email: alexanderhmendes@gmail.com
description: An application for viewing and manipulating TEI XML documents in table form.
repository: alexandermendes/tei-viewer

# Build settings
incremental: true
exclude: [vendor]
sass:
  style: :compressed