# Site settings
title: TEI Viewer
author: Alexander Mendes
author-url: https://github.com/alexandermendes
github_url: https://github.com/alexandermendes/teiviewer
email: alexanderhmendes@gmail.com
description: An application for viewing and manipulating TEI XML documents in table form.
repository: alexandermendes/tei-viewer
sample-url: http://www.dropbox.com/s/t0ahw14fk75atkt/tei.json?dl=1
sample-citation: Sample taken from the British Library's Hebrew manuscripts collections 

# Build settings
incremental: true
exclude:
  - 'test/'
  - 'node_modules/'
  - 'Gruntfile.js'
  - 'package.json'
  - 'LICENSE'
  - 'README.md'
markdown: kramdown
highlighter: pygments
sass:
  style: compressed
collections:
  tables:
    output: true
  docs:
    output: true