# Site settings
title: TEI Viewer
author: Alexander Mendes
author-url: https://github.com/alexandermendes
email: alexanderhmendes@gmail.com
description: An application for viewing and manipulating TEI XML documents in table form.
sample-url: https://cdn.rawgit.com/alexandermendes/tei-viewer/master/sample.json.js
sample-citation: Sample taken from the British Library's Hebrew manuscripts collections
repository: alexandermendes/tei-viewer
baseurl: /tei-viewer

# Build settings
incremental: true
exclude:
  - 'test/'
  - 'node_modules/'
  - 'Gruntfile.js'
  - 'package.json'
  - 'LICENSE'
  - 'README.md'
  - '*.log'
markdown: kramdown
sass:
  style: compressed
collections:
  tables:
    output: true
  docs:
    output: true