# Site settings
title: TEI Viewer
author: Alexander Mendes
author-url: https://github.com/alexandermendes
email: alexanderhmendes@gmail.com
description: An HTML5 application for viewing and manipulating TEI XML documents in table form.
repository: alexandermendes/tei-viewer
markdown: kramdown
highlighter: pygments

# Build settings
incremental: true
exclude:
  - 'js/'
  - 'test/'
  - 'vendor/'
  - 'node_modules/'
  - 'Gruntfile.js'
  - 'package.json'
  - 'LICENSE'
sass:
  style: :compressed